### ISSUE TITLE
About support npm and node version

### ISSUE THREAD

**Issue by LronDC** [karmada-io/website#114]
```shell
> npm -v
> 8.12.1

> node -v
> v18.4.0
```
When executing `npm install`, got this error:
![image](https://user-images.githubusercontent.com/59912384/179448086-be61fd4f-44c2-4b3a-8d38-27cf2c305b17.png)

It looks like is nodejieba's supporting issue, can it be fixed on karmada website?

**Comment by Arhell** [comment]
I think this problem will be solved by this https://github.com/karmada-io/website/pull/91

**Comment by Arhell** [comment]
@LronDC  check please i update website

**Comment by LronDC** [comment]
> @LronDC check please i update website

@Arhell Sorry, I fetched code and run `npm install`, still the same error, so I won't put another picture here, but I can share the error log if you want. Looks like this problem not fixed, or did I do something stupid to make it wrong?

**Comment by RainbowMango** [comment]
@Arhell @rgrupesh Any comments?

**Comment by Arhell** [comment]
Try delete package-lock.json file node module folder and re-install.

**Comment by rgrupesh** [comment]
> @Arhell @rgrupesh Any comments?

use latest node LTS Version: 16.17.0

**Comment by RainbowMango** [comment]
> Try delete package-lock.json file node module folder and re-install.

Still not work for me.

**Comment by RainbowMango** [comment]
> use latest node LTS Version: 16.17.0

@rgrupesh does this work for you?

**Comment by Arhell** [comment]
@RainbowMango  i also use 16+ v

**Comment by rgrupesh** [comment]
> 

Yeah

**Comment by LronDC** [comment]
So should the project make a state somewhere that `website` supports node version of v16+ so people won't face this problem? But I'm not sure if version 16.17 is the right one

**Comment by RainbowMango** [comment]
Yes, we should document the required version, but before that, we need to figure out if the version is the root cause.
I'll try with the latest node version and will get back to you then.

**Comment by RainbowMango** [comment]
Bad news, after I uninstall node and reinstall the latest `v16.17.0`, it still not work for me.
```
-bash-4.2# node -v 
v16.17.0
-bash-4.2# npm -v 
8.15.0
```

```
-bash-4.2# npm install
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm ERR! code 1
npm ERR! path /root/go/src/github.com/karmada-io/website/node_modules/nodejieba
npm ERR! command failed
npm ERR! command sh /tmp/install-4f3ac1ee.sh
npm ERR! make: Entering directory '/root/go/src/github.com/karmada-io/website/node_modules/nodejieba/build'
npm ERR!   CXX(target) Release/obj.target/nodejieba/lib/index.o
npm ERR! make: Leaving directory '/root/go/src/github.com/karmada-io/website/node_modules/nodejieba/build'
npm ERR! Failed to execute '/usr/local/node-v16.17.0-linux-x64/bin/node /usr/local/node-v16.17.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/go/src/github.com/karmada-io/website/node_modules/nodejieba/build/Release/nodejieba.node --module_name=nodejieba --module_path=/root/go/src/github.com/karmada-io/website/node_modules/nodejieba/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
```

**Comment by Arhell** [comment]
Try remove all node modules package-lock.json and re-install 
usually if I have such problems it helps me

**Comment by SAMZONG** [comment]
What is your computer system and chip?

maybe you need find why `nodejieba` not working ?

> node version 16.17.0 is successful on mac mac m2

![CleanShot 2022-09-22 at 11 18 03](https://user-images.githubusercontent.com/13782141/191650779-a525b505-1b6c-4b3c-8fb2-4a979efa5c0b.jpg)

**Comment by RainbowMango** [comment]
> What is your computer system and chip?
```
-bash-4.2# uname -a 
Linux ecs-d8b6 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

> maybe you need find why nodejieba not working ?

I don't know how to figure out why it's not working.
I tried to install it, but still fails:
```
-bash-4.2# npm install nodejieba
npm ERR! code 1
npm ERR! path /root/node_modules/nodejieba
npm ERR! command failed
npm ERR! command sh /tmp/install-61ba1f55.sh
npm ERR! make: Entering directory '/root/node_modules/nodejieba/build'
npm ERR!   CXX(target) Release/obj.target/nodejieba/lib/index.o
npm ERR! make: Leaving directory '/root/node_modules/nodejieba/build'
npm ERR! Failed to execute '/usr/local/node-v16.17.0-linux-x64/bin/node /usr/local/node-v16.17.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/node_modules/nodejieba/build/Release/nodejieba.node --module_name=nodejieba --module_path=/root/node_modules/nodejieba/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
```


<details>
  <summary><mark><font color=darkred>For the whole logs, you can see from here:</font></mark></summary>

```
-bash-4.2# npm install nodejieba
npm ERR! code 1
npm ERR! path /root/node_modules/nodejieba
npm ERR! command failed
npm ERR! command sh /tmp/install-61ba1f55.sh
npm ERR! make: Entering directory '/root/node_modules/nodejieba/build'
npm ERR!   CXX(target) Release/obj.target/nodejieba/lib/index.o
npm ERR! make: Leaving directory '/root/node_modules/nodejieba/build'
npm ERR! Failed to execute '/usr/local/node-v16.17.0-linux-x64/bin/node /usr/local/node-v16.17.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/node_modules/nodejieba/build/Release/nodejieba.node --module_name=nodejieba --module_path=/root/node_modules/nodejieba/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@16.17.0 | linux | x64
npm ERR! node-pre-gyp info check checked for "/root/node_modules/nodejieba/build/Release/nodejieba.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/yanyiwu/nodejieba/releases/download/v2.6.0/nodejieba-v2.6.0-node-v93-linux-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/yanyiwu/nodejieba/releases/download/v2.6.0/nodejieba-v2.6.0-node-v93-linux-x64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for nodejieba@2.6.0 and node@16.17.0 (node-v93 ABI, glibc) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/yanyiwu/nodejieba/releases/download/v2.6.0/nodejieba-v2.6.0-node-v93-linux-x64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.17.0 | linux | x64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.17.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.6.8 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/node-v16.17.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/node_modules/nodejieba/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/node-v16.17.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/16.17.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.17.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/node-v16.17.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.17.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/root/node_modules/nodejieba',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.17.0 | linux | x64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! g++: error: unrecognized command line option ‘-std=gnu++14’
npm ERR! make: *** [nodejieba.target.mk:116: Release/obj.target/nodejieba/lib/index.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/node-v16.17.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 3.10.0-1062.12.1.el7.x86_64
npm ERR! gyp ERR! command "/usr/local/node-v16.17.0-linux-x64/bin/node" "/usr/local/node-v16.17.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/root/node_modules/nodejieba/build/Release/nodejieba.node" "--module_name=nodejieba" "--module_path=/root/node_modules/nodejieba/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
npm ERR! gyp ERR! cwd /root/node_modules/nodejieba
npm ERR! gyp ERR! node -v v16.17.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/node-v16.17.0-linux-x64/bin/node /usr/local/node-v16.17.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/node_modules/nodejieba/build/Release/nodejieba.node --module_name=nodejieba --module_path=/root/node_modules/nodejieba/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1093:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Linux 3.10.0-1062.12.1.el7.x86_64
npm ERR! node-pre-gyp ERR! command "/usr/local/node-v16.17.0-linux-x64/bin/node" "/root/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /root/node_modules/nodejieba
npm ERR! node-pre-gyp ERR! node -v v16.17.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-09-22T03_30_39_864Z-debug-0.log
-bash-4.2# npm -v 
8.15.0
-bash-4.2# node version
node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module '/root/prow/husheng/version'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

</details>

**Comment by SAMZONG** [comment]
I may not be able to answer your question accurately!

However, the problem has clear, It's should be caused by problems in node or `nodejieba`, 


I am not find any dependency with `nodejieba` in the project, maybe u can re-fork the project and retry after in a clear environment

**Comment by rgrupesh** [comment]
@RainbowMango Are you still facing this issue?

**Comment by RainbowMango** [comment]
Yeah, I don't have enough time for this recently.

**Comment by SAMZONG** [comment]
Latest update: how to recommend a node version, suggested to refer to the upstream project, add .nvmrc file. This provides good guidance for users of Node.js.

https://github.com/facebook/docusaurus/blob/main/.nvmrc

**Comment by SAMZONG** [comment]
> Latest update: how to recommend a node version, suggested to refer to the upstream project, add .nvmrc file. This provides good guidance for users of Node.js.最近更新：如何推荐node版本，建议参考上游项目，添加.nvmrc文件。这为 Node.js 的用户提供了很好的指导。
> 
> https://github.com/facebook/docusaurus/blob/main/.nvmrc

If necessary, you can assign this task to me.

**Comment by LronDC** [comment]
Follow-up update: 
```shell
> npm -v
8.15.0
> node -v
v16.17.0
```
It works for me now.

**Comment by SAMZONG** [comment]
ok, pls close this issue @LronDC

**Comment by LronDC** [comment]
> maybe u can re-fork the project and retry after in a clear environment

Did this.
